version: '3.9'
services:
  app:
    container_name: bs-ms-core
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    networks:
      - bs-network
networks:
  bs-network:
    external: true
